; PlatformIO Project Configuration
; See https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

[env]
framework = arduino
monitor_speed = 115200

[env:esp32]
platform = espressif32
board = esp32dev
board_build.mcu = esp32
board_build.f_cpu = 240000000L

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.usb_mode = otg
board_build.usbCDC = disabled

[env:stm32h7]
platform = ststm32
board = stm32h7b3i_disco
board_build.mcu = stm32h743vibt
build_flags = -DBOARD_HAS_PSRAM

[env:pico]
platform = raspberrypi
board = rpipico
board_build.mcu = rp2040
board_build.f_cpu = 133000000